# 공통부분     
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    
logging:
  level:
    '[org.apache.ibatis]': DEBUG
    '[com.example.demo]': DEBUG
     
---
spring:
  profiles:  - dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver    hikari:
      username: root
      password: root      maximum-pool-size: 4
      connection-test-query: SELECT 1
      connection-timeout: 3000
    
---
spring:  profiles:  - default 
  datasource:    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  h2:    console:      enabled: true
      path: /h2-console