
# 공통부분     
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    
logging:
  level:
    '[org.apache.ibatis]': DEBUG
    '[com.example.demo]': DEBUG
    
server:  port: 8080
  
spring:
  profiles:
    active:
    - dev 
---
spring:
  profiles:  - dev
  jpa:
    properties:
      hibernate:
        format_sql: true        #use_sql_comments: true    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl      ddl-auto: update    show-sql: true
  
  datasource:
    initialization-mode: never
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8&passwordCharacterEncoding=UTF-8    hikari:
      username: root
      password: root      maximum-pool-size: 4
      connection-test-query: SELECT 1
      connection-timeout: 3000

  quartz:
    scheduler-name: QuartzScheduler
    jdbc:
      initialize-schema: never
    properties:
      job-store-type: jdbc
      org:
        quartz:
          scheduler:
            instanceName: QuartzScheduler
            instanceId: AUTO
          threadPool.threadCount: 2
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
            useProperties: true
    
---
spring:  profiles:  - default 
  datasource:    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  h2:    console:      enabled: true
      path: /h2-console
  quartz:
    scheduler-name: QuartzScheduler
    jdbc:
      initialize-schema: always
    properties:
      job-store-type: memory